// templates/vue/xcm-api/src/wallet/evm/WalletKindSelector.vue
<script setup lang="ts">
export type WalletKind = "substrate" | "evm";

const WALLET_KIND_OPTIONS: { value: WalletKind; label: string }[] = [
  { value: "substrate", label: "Substrate" },
  { value: "evm", label: "EVM" },
];

defineProps<{
  activeWalletKind: WalletKind;
}>();

const emit = defineEmits<{
  "update:activeWalletKind": [kind: WalletKind];
}>();
</script>

<template>
  <div>
    <h4>Wallet type:</h4>
    <select
      :value="activeWalletKind"
      @change="
        emit(
          'update:activeWalletKind',
          ($event.target as HTMLSelectElement).value as WalletKind,
        )
      "
    >
      <option
        v-for="{ value, label } in WALLET_KIND_OPTIONS"
        :key="value"
        :value="value"
      >
        {{ label }}
      </option>
    </select>
  </div>
</template>

// templates/react/xcm-api/src/wallet/evm/WalletKindSelector.tsx
/* EVM_FEATURE — entire file */

import type { FC } from "react";

export type WalletKind = "substrate" | "evm";

export type WalletKindSelectorProps = {
  activeWalletKind: WalletKind;
  setActiveWalletKind: (kind: WalletKind) => void;
};

const WALLET_KIND_OPTIONS: { value: WalletKind; label: string }[] = [
  { value: "substrate", label: "Substrate" },
  { value: "evm", label: "EVM" },
];

export const WalletKindSelector: FC<WalletKindSelectorProps> = ({
  activeWalletKind,
  setActiveWalletKind,
}) => (
  <div>
    <h4>Wallet type:</h4>
    <select
      value={activeWalletKind}
      onChange={(e) => setActiveWalletKind(e.target.value as WalletKind)}
    >
      {WALLET_KIND_OPTIONS.map(({ value, label }) => (
        <option key={value} value={value}>
          {label}
        </option>
      ))}
    </select>
  </div>
);
