// templates/react/xcm-api/src/XcmTransferForm.tsx
import axios from "axios";
import { useState, useMemo, FormEvent, FC, useEffect } from "react";
import { API_URL } from "./consts";
import type { AssetInfo, FormValues } from "./types";
import { filterChainsForWallet } from "./evm";

type Props = {
  onSubmit: (values: FormValues) => void;
  loading: boolean;
  originChain: string;
  onOriginChange: (origin: string) => void;
  isEvmOrigin?: boolean;
};

const TransferForm: FC<Props> = ({
  onSubmit,
  loading,
  originChain,
  onOriginChange,
  isEvmOrigin = false,
}) => {
  const [chains, setChains] = useState<string[]>([]);
  const [destinationChain, setDestinationChain] = useState("Hydration");
  const [supportedAssets, setSupportedAssets] = useState<AssetInfo[]>([]);
  const [currencyOptionId, setCurrencyOptionId] = useState("");
  const [currencyTo, setCurrencyTo] = useState("DOT");
  const [swapEnabled, setSwapEnabled] = useState(false);
  const [exchange, setExchange] = useState("");
  const [recipient, setRecipient] = useState(
    "5F5586mfsnM6durWRLptYt3jSUs55KEmahdodQ5tQMr9iY96",
  );
  const [amount, setAmount] = useState("5");

  const fetchChains = async () => {
    const response = await axios.get(`${API_URL}/chains`);
    setChains(response.data);
  };

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void fetchChains();
  }, []);

  const originChains = useMemo(
    () => filterChainsForWallet(chains, isEvmOrigin),
    [chains, isEvmOrigin],
  );

  useEffect(() => {
    const fetchAssets = async () => {
      const response = await axios.get(
        `${API_URL}/supported-assets?origin=${originChain}&destination=${destinationChain}`,
      );
      const assets = response.data as AssetInfo[];
      setSupportedAssets(assets);
    };
    void fetchAssets();
  }, [originChain, destinationChain]);

  const currencyMap = useMemo(
    () =>
      supportedAssets.reduce(
        (map: Record<string, AssetInfo>, asset: AssetInfo) => {
          const key = `${asset.symbol ?? "NO_SYMBOL"}-${JSON.stringify(asset.location)}`;
          map[key] = asset;
          return map;
        },
        {},
      ),
    [supportedAssets],
  );

  const currencyOptions = useMemo(
    () =>
      Object.keys(currencyMap).map((key) => ({
        value: key,
        label: `${currencyMap[key].symbol ?? "Unknown"} - ${currencyMap[key].assetId ?? "Location"}`,
      })),
    [currencyMap],
  );

  useEffect(() => {
    if (currencyOptions.length > 0) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setCurrencyOptionId(currencyOptions[currencyOptions.length - 1].value);
    }
  }, [currencyOptions]);

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    onSubmit({
      from: originChain,
      to: destinationChain,
      recipient,
      amount,
      currency: currencyMap[currencyOptionId],
      swapEnabled,
      currencyTo: swapEnabled ? currencyTo : undefined,
      exchange: swapEnabled && exchange ? exchange : undefined,
    });
  };

  return (
    <form onSubmit={handleSubmit}>
      <label>
        Origin chain
        <select
          value={originChain}
          onChange={(e) => onOriginChange(e.target.value)}
          required
        >
          {originChains.map((chain) => (
            <option key={chain} value={chain}>
              {chain}
            </option>
          ))}
        </select>
      </label>

      <label>
        Destination chain
        <select
          value={destinationChain}
          onChange={(e) => setDestinationChain(e.target.value)}
          required
        >
          {chains.map((chain) => (
            <option key={chain} value={chain}>
              {chain}
            </option>
          ))}
        </select>
      </label>

      <label>
        Currency
        <select
          value={currencyOptionId}
          onChange={(e) => setCurrencyOptionId(e.target.value)}
          required
        >
          {currencyOptions.map((option) => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </select>
      </label>

      <label>
        Recipient address
        <input
          type="text"
          value={recipient}
          onChange={(e) => setRecipient(e.target.value)}
          required
        />
      </label>

      <label>
        Amount
        <input
          type="number"
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
          required
        />
      </label>

      {!isEvmOrigin && (
        <>
          <button
            type="button"
            className="secondary"
            onClick={() => setSwapEnabled((prev) => !prev)}
          >
            {swapEnabled ? "- Remove Swap" : "+ Add Swap"}
          </button>

          {swapEnabled && (
            <>
              <label>
                Exchange
                <input
                  type="text"
                  value={exchange}
                  onChange={(e) => setExchange(e.target.value)}
                  placeholder="Leave empty for auto"
                />
              </label>

              <label>
                Currency To
                <input
                  type="text"
                  value={currencyTo}
                  onChange={(e) => setCurrencyTo(e.target.value)}
                  required
                />
              </label>
            </>
          )}
        </>
      )}

      <button type="submit" disabled={loading}>
        {loading ? "Submitting..." : "Submit transaction"}
      </button>
    </form>
  );
};

export default TransferForm;

// templates/vue/xcm-api/src/XcmTransferForm.vue
<script setup lang="ts">
import axios from "axios";
import { ref, computed, watch, onMounted } from "vue";
import { API_URL } from "./consts";
import type { AssetInfo, FormValues } from "./types";
import { filterChainsForWallet } from "./evm";

const props = defineProps<{
  loading: boolean;
  originChain: string;
  isEvmOrigin?: boolean;
}>();

const emit = defineEmits<{
  submit: [values: FormValues];
  originChange: [origin: string];
}>();

const chains = ref<string[]>([]);
const destinationChain = ref("Hydration");
const supportedAssets = ref<AssetInfo[]>([]);
const currencyOptionId = ref("");
const currencyTo = ref("DOT");
const swapEnabled = ref(false);
const exchange = ref("");
const recipient = ref(
  "5F5586mfsnM6durWRLptYt3jSUs55KEmahdodQ5tQMr9iY96",
);
const amount = ref("5");

const fetchChains = async () => {
  const response = await axios.get(`${API_URL}/chains`);
  chains.value = response.data as string[];
};

onMounted(() => {
  void fetchChains();
});

const originChains = computed(() =>
  filterChainsForWallet(chains.value, props.isEvmOrigin ?? false),
);

watch(
  () => props.originChain,
  () => {},
);

watch(
  [() => props.originChain, destinationChain],
  async () => {
    const response = await axios.get(
      `${API_URL}/supported-assets?origin=${props.originChain}&destination=${destinationChain.value}`,
    );
    supportedAssets.value = response.data as AssetInfo[];
  },
  { immediate: true },
);

const currencyMap = computed(() =>
  supportedAssets.value.reduce(
    (map: Record<string, AssetInfo>, asset: AssetInfo) => {
      const key = `${asset.symbol ?? "NO_SYMBOL"}-${JSON.stringify(asset.location)}`;
      map[key] = asset;
      return map;
    },
    {},
  ),
);

const currencyOptions = computed(() =>
  Object.keys(currencyMap.value).map((key) => ({
    value: key,
    label: `${currencyMap.value[key].symbol ?? "Unknown"} - ${currencyMap.value[key].assetId ?? "Location"}`,
  })),
);

watch(
  currencyOptions,
  (opts) => {
    if (opts.length > 0) {
      currencyOptionId.value = opts[opts.length - 1].value;
    }
  },
  { immediate: true },
);

const onOriginSelect = (e: Event) => {
  const value = (e.target as HTMLSelectElement).value;
  emit("originChange", value);
};

const handleSubmit = (e: Event) => {
  e.preventDefault();
  emit("submit", {
    from: props.originChain,
    to: destinationChain.value,
    recipient: recipient.value,
    amount: amount.value,
    currency: currencyMap.value[currencyOptionId.value],
    swapEnabled: swapEnabled.value,
    currencyTo: swapEnabled.value ? currencyTo.value : undefined,
    exchange: swapEnabled.value && exchange.value ? exchange.value : undefined,
  });
};
</script>

<template>
  <form @submit="handleSubmit">
    <label>
      Origin chain
      <select
        :value="originChain"
        required
        @change="onOriginSelect"
      >
        <option
          v-for="chain in originChains"
          :key="chain"
          :value="chain"
        >
          {{ chain }}
        </option>
      </select>
    </label>

    <label>
      Destination chain
      <select
        v-model="destinationChain"
        required
      >
        <option
          v-for="chain in chains"
          :key="chain"
          :value="chain"
        >
          {{ chain }}
        </option>
      </select>
    </label>

    <label>
      Currency
      <select
        v-model="currencyOptionId"
        required
      >
        <option
          v-for="option in currencyOptions"
          :key="option.value"
          :value="option.value"
        >
          {{ option.label }}
        </option>
      </select>
    </label>

    <label>
      Recipient address
      <input
        v-model="recipient"
        type="text"
        required
      >
    </label>

    <label>
      Amount
      <input
        v-model="amount"
        type="number"
        required
      >
    </label>

    <template v-if="!isEvmOrigin">
      <button
        type="button"
        class="secondary"
        @click="swapEnabled = !swapEnabled"
      >
        {{ swapEnabled ? "- Remove Swap" : "+ Add Swap" }}
      </button>

      <template v-if="swapEnabled">
        <label>
          Exchange
          <input
            v-model="exchange"
            type="text"
            placeholder="Leave empty for auto"
          >
        </label>

        <label>
          Currency To
          <input
            v-model="currencyTo"
            type="text"
            required
          >
        </label>
      </template>
    </template>

    <button
      type="submit"
      :disabled="loading"
    >
      {{ loading ? "Submitting..." : "Submit transaction" }}
    </button>
  </form>
</template>
