// templates/react/xcm-sdk/src/wallet/evm/EvmWalletControls.tsx
/* EVM_FEATURE — entire file */

import type { FC } from "react";
import type { EvmAccountOption } from "./useEvmWallet";

export type EvmWalletControlsProps = {
  accounts: EvmAccountOption[];
  selectedAddress: string | undefined;
  onConnectClick: () => void;
  onAccountChange: (address: string) => void;
  onDisconnect?: () => void;
};

export const EvmWalletControls: FC<EvmWalletControlsProps> = ({
  accounts,
  selectedAddress,
  onConnectClick,
  onAccountChange,
  onDisconnect,
}) => (
  <div className="formHeader">
    {accounts.length === 0 ? (
      <button type="button" onClick={onConnectClick}>
        Connect Wallet
      </button>
    ) : (
      <div>
        <h4>Select account:</h4>
        <select
          value={selectedAddress ?? ""}
          onChange={(e) => onAccountChange(e.target.value)}
        >
          {accounts.map(({ label, address }) => (
            <option key={address} value={address}>
              {label} — {address}
            </option>
          ))}
        </select>
      </div>
    )}
    {selectedAddress && onDisconnect && (
      <button type="button" className="secondary" onClick={onDisconnect}>
        Disconnect
      </button>
    )}
  </div>
);

// templates/vue/xcm-sdk/src/wallet/evm/EvmWalletControls.vue
<script setup lang="ts">
import type { EvmAccountOption } from "./useEvmWallet";

defineProps<{
  accounts: EvmAccountOption[];
  selectedAddress: string | undefined;
  onConnectClick: () => void;
  onAccountChange: (address: string) => void;
  onDisconnect?: () => void;
}>();
</script>

<template>
  <div class="formHeader">
    <button
      v-if="accounts.length === 0"
      type="button"
      @click="onConnectClick"
    >
      Connect Wallet
    </button>
    <div v-else>
      <h4>Select account:</h4>
      <select
        :value="selectedAddress ?? ''"
        @change="onAccountChange(($event.target as HTMLSelectElement).value)"
      >
        <option
          v-for="{ label, address } in accounts"
          :key="address"
          :value="address"
        >
          {{ label }} — {{ address }}
        </option>
      </select>
    </div>
    <button
      v-if="selectedAddress && onDisconnect"
      type="button"
      class="secondary"
      @click="onDisconnect"
    >
      Disconnect
    </button>
  </div>
</template>
