// implementation/react/client/papi/wallet/PapiWalletControls.tsx
import type { FC } from "react";

type WalletAccountOption = {
  address: string;
  name?: string;
};

export type PapiWalletControlsProps = {
  extensionNames: string[];
  selectedExtensionName: string | null;
  accounts: WalletAccountOption[];
  selectedAddress: string | undefined;
  onConnectClick: () => void;
  onExtensionChange: (name: string) => void;
  onAccountChange: (address: string) => void;
};

export const PapiWalletControls: FC<
PapiWalletControlsProps
> = ({
  extensionNames,
  selectedExtensionName,
  accounts,
  selectedAddress,
  onConnectClick,
  onExtensionChange,
  onAccountChange,
}) => (
  <div className="formHeader">
    {extensionNames.length > 0 ? (
      <div>
        <h4>Select extension:</h4>
        <select
          value={selectedExtensionName ?? ""}
          onChange={(e) => onExtensionChange(e.target.value)}
        >
          <option disabled value="">
            -- select an option --
          </option>
          {extensionNames.map((name) => (
            <option key={name} value={name}>
              {name}
            </option>
          ))}
        </select>
      </div>
    ) : (
      <button type="button" onClick={onConnectClick}>
        Connect Wallet
      </button>
    )}
    {accounts.length > 0 && (
      <div>
        <h4>Select account:</h4>
        <select
          value={selectedAddress ?? ""}
          onChange={(e) => onAccountChange(e.target.value)}
        >
          {accounts.map(({ name, address }) => (
            <option key={address} value={address}>
              {name} - {address}
            </option>
          ))}
        </select>
      </div>
    )}
  </div>
);

// templates/vue/xcm-sdk/src/wallet/papi/PapiWalletControls.vue
<script setup lang="ts">
import type { InjectedPolkadotAccount } from "polkadot-api/pjs-signer";

defineProps<{
  extensionNames: string[];
  selectedExtensionName: string | null;
  accounts: InjectedPolkadotAccount[];
  selectedAddress: string | undefined;
  onConnectClick: () => void;
  onExtensionChange: (name: string) => void;
  onAccountChange: (address: string) => void;
}>();
</script>

<template>
  <div class="formHeader">
    <div v-if="extensionNames.length > 0">
      <h4>Select extension:</h4>
      <select
        :value="selectedExtensionName ?? ''"
        @change="
          ($event.target as HTMLSelectElement).value &&
            onExtensionChange(($event.target as HTMLSelectElement).value)
        "
      >
        <option
          disabled
          value=""
        >
          -- select an option --
        </option>
        <option
          v-for="name in extensionNames"
          :key="name"
          :value="name"
        >
          {{ name }}
        </option>
      </select>
    </div>
    <button
      v-else
      type="button"
      @click="onConnectClick"
    >
      Connect Wallet
    </button>

    <div v-if="accounts.length > 0">
      <h4>Select account:</h4>
      <select
        :value="selectedAddress ?? ''"
        @change="onAccountChange(($event.target as HTMLSelectElement).value)"
      >
        <option
          v-for="{ name, address } in accounts"
          :key="address"
          :value="address"
        >
          {{ name }} - {{ address }}
        </option>
      </select>
    </div>
  </div>
</template>
